feat:support config inject server host
alibaba/lowcode-tools pull request #15
Opened 2022-09-07 13:48 UTC by DiligentNezha

背景：在本机开发好物料，注入到demo项目没有问题，同局域网下的其他主机访问则不能注入物料，因此修改部分逻辑支持该场景，修改逻辑如下，lowcode-plugin-inject 支持通过请求参数控制获取注入资源的主机地址，注入服务监听端口修改为0.0.0.0，返回的注入资源路径以devServer 当前运行的主机Ip为准

2022-09-14 07:05 UTC, eternalsky commented
为什么要其他主机访问，这可能存在一定的安全问题。

2022-09-14 14:29 UTC, DiligentNezha commented
> 主要是局域网下其他主机访问，分享给同事，查看新开发的物料效果。安全问题，我看上一个pull request 已经把 inject server host 改成 0.0.0.0 了，也就是在局域网环境下，如果inject server 主机没有开防火墙的情况下，同网段下其他主机也可以访问到注入资源，我这里只是把返回体中的资源host改成inject server 主机的Ip了，另外，inject 端在 debug 后加上injectServerHost参数才会生效，如果你觉得还是有安全问题，那在 alt 插件那里再加个开关，默认相应体的资源host 按照127.0.0.1 返回，打开的话按照主机 IP 返回。

2022-09-15 06:07 UTC, eternalsky commented
build-plugin-inject 开 0.0.0.0 这个我觉得没有问题，包括这个 pr 里包含的部分。开通这个的主要目的，是为了防止一些系统。localhost 和 127.0.0.1 不匹配造成的使用问题，但这个属于主动行为，本身是不具有危害性的。但在 lowcode-plugin-inject 里添加的话感觉不是很妥当，尤其是通过 query 就可以开启，那么完全可以在用户不知情的情况下，攻击者发送有害链接来进行脚本注入，这个还是很危险的。因此 inject 中只会接受链接本地的请求。

2022-09-16 22:21 UTC, DiligentNezha commented
> build-plugin-inject 开 0.0.0.0 这个我觉得没有问题，包括这个 pr 里包含的部分。开通这个的主要目的，是为了防止一些系统。localhost 和 127.0.0.1 不匹配造成的使用问题，但这个属于主动行为，本身是不具有危害性的。但在 lowcode-plugin-inject 里添加的话感觉不是很妥当，尤其是通过 query 就可以开启，那么完全可以在用户不知情的情况下，攻击者发送有害链接来进行脚本注入，这个还是很危险的。因此 inject 中只会接受链接本地的请求。

我非常认可你说的安全问题，但是我提到的需求确实是有的，那把 query 开启改为插件启动参数 injectServerHost，同时对获/apis/injectInfo 接口的响应资源 url host 和 injectServerHost 进行匹配校验来提升安全性，你看是否可以接受

2022-09-23 01:58 UTC, eternalsky commented
> > build-plugin-inject 开 0.0.0.0 这个我觉得没有问题，包括这个 pr 里包含的部分。开通这个的主要目的，是为了防止一些系统。localhost 和 127.0.0.1 不匹配造成的使用问题，但这个属于主动行为，本身是不具有危害性的。但在 lowcode-plugin-inject 里添加的话感觉不是很妥当，尤其是通过 query 就可以开启，那么完全可以在用户不知情的情况下，攻击者发送有害链接来进行脚本注入，这个还是很危险的。因此 inject 中只会接受链接本地的请求。
> 
> 我非常认可你说的安全问题，但是我提到的需求确实是有的，那把 query 开启改为插件启动参数 injectServerHost，同时对获/apis/injectInfo 接口的响应资源 url host 和 injectServerHost 进行匹配校验来提升安全性，你看是否可以接受

改为插件参数启动我觉得安全性上会好一些，这样就不是插件的默认行为，而是由平台选择性开启的。安全性可以由平台的维护者自己把控。

2022-09-25 00:28 UTC, DiligentNezha commented
> > > build-plugin-inject 开 0.0.0.0 这个我觉得没有问题，包括这个 pr 里包含的部分。开通这个的主要目的，是为了防止一些系统。localhost 和 127.0.0.1 不匹配造成的使用问题，但这个属于主动行为，本身是不具有危害性的。但在 lowcode-plugin-inject 里添加的话感觉不是很妥当，尤其是通过 query 就可以开启，那么完全可以在用户不知情的情况下，攻击者发送有害链接来进行脚本注入，这个还是很危险的。因此 inject 中只会接受链接本地的请求。
> > 
> > 
> > 我非常认可你说的安全问题，但是我提到的需求确实是有的，那把 query 开启改为插件启动参数 injectServerHost，同时对获/apis/injectInfo 接口的响应资源 url host 和 injectServerHost 进行匹配校验来提升安全性，你看是否可以接受
> 
> 改为插件参数启动我觉得安全性上会好一些，这样就不是插件的默认行为，而是由平台选择性开启的。安全性可以由平台的维护者自己把控。匹配个人感觉意义不大，如果真的是为了攻击，采取同源的策略基本上也是默认的选择，感觉无法用来过滤。

lowcode-plugin-inject injectServerHost 修改为插件的配置项像形式了，同时把一些由于编辑器格式化引起的非必要改动也处理掉了，麻烦你看看

2022-09-28 02:06 UTC, eternalsky requested changes

2022-09-28 02:06 UTC, eternalsky commented on packages/lowcode-plugin-inject/src/index.tsx
> +export function getInjectServerHost() {
这个方法应该放在 utils 中，现在是循环引用的情况，而且 utils 引 index 也不太对

2022-09-28 02:06 UTC, eternalsky commented on packages/lowcode-plugin-inject/src/index.tsx
> +    title: '注入资源的主机地址',
这个 title 的描述好像不对，另外按照规范，这部分应该写在 package.json 里

2022-09-28 02:06 UTC, eternalsky commented on packages/build-plugin-alt/src/index.ts
> +      const injectServerHost = server['urls'].lanUrlForConfig;
这个 api 是从哪里来的，按照文档，第一个参数应该只有 url 和 devServer 两个字段，另外这里为什么要把触发时机从 before.start.load 向后延迟到 before.start.devServer ?

2022-09-28 12:17 UTC, DiligentNezha commented on packages/lowcode-plugin-inject/src/index.tsx
> +export function getInjectServerHost() {
好的，我调整一下

2022-09-28 12:29 UTC, DiligentNezha commented on packages/lowcode-plugin-inject/src/index.tsx
> +    title: '注入资源的主机地址',
要不你给改一个合适的title吧，你说的规范是在哪里？我没有找到相关插件的开发规范，我看issue 里有人这样写，就按自己的理解写的

2022-09-28 13:15 UTC, DiligentNezha commented on packages/build-plugin-alt/src/index.ts
> +      const injectServerHost = server['urls'].lanUrlForConfig;
这个 server 实际是个 IOnHookCallbackArg 类型的对象，我名字起的不合适，
<img width="447" alt="image" src="https://user-images.githubusercontent.com/20829924/192786167-a6267d20-5e43-4ad5-856d-16c0e3572d9f.png">，在before.start.devServer事件中，值打印如下，
<img width="835" alt="image" src="https://user-images.githubusercontent.com/20829924/192787104-15122698-06a6-46ac-b00c-5a889dff9087.png">
，触发时机延后主要是获取本机IP，传递给makeInjectInfo 方法，使其在生成 /apis/injectInfo 接口的响应体中返回的资源路径是本机IP，lowcode-plugin-inject 插件配合 injectServerHost 参数实现本次 pr 的功能

2022-09-30 00:24 UTC, DiligentNezha commented on packages/build-plugin-alt/src/index.ts
> +      const injectServerHost = server['urls'].lanUrlForConfig;
事件换回 before.start.load，makeInjectInfo 初始化传入的 host 由 build-script 的 --host 参数决定，把自主权交给用户

2022-10-14 03:33 UTC, eternalsky commented
基本 ok 了，我先合并，再稍作修改后发布。

2022-10-14 03:34 UTC, merged

2022-10-14 12:20 UTC, DiligentNezha commented
> 基本 ok 了，我先合并，再稍作修改后发布。

好的，给语雀添加插件的使用说明有什么要求吗？想补充一下插件的使用说明

2022-11-09 12:51 UTC, eternalsky commented
> 

抱歉，合完之后一直忘发了，build-plugin-alt 和 lowcode-plugin-inject 都发布了beta 版。用法详见 CHANGELOG
https://github.com/alibaba/lowcode-tools/blob/main/packages/build-plugin-alt/CHANGELOG.md
https://github.com/alibaba/lowcode-tools/blob/main/packages/lowcode-plugin-inject/HISTORY.md